# .github/workflows/main.yml

name: Deploy to AWS Elastic Beanstalk

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Checkout kode dari repositori
    - name: Checkout source code
      uses: actions/checkout@v3

    # Langkah 2: Konfigurasi kredensial AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2 # GANTI dengan region AWS Anda (lihat di URL Elastic Beanstalk)

    # Langkah 3: Membuat file zip dari kode aplikasi
    - name: Zip our application code
      run: zip -r deploy.zip . -x ".git/*" ".github/*"

    # Langkah 4: Deploy ke Elastic Beanstalk
    - name: Deploy to Production Environment
      if: github.ref == 'refs/heads/main'
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        # PASTIKAN SEMUA BARIS DI BAWAH INI ADA DAN INDENTASINYA BENAR
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # <-- PERIKSA BARIS INI DENGAN SEKSAMA
        application_name: WebAppSaya
        environment_name: WebAppSaya-prod-env
        region: ap-southeast-2 # Pastikan region Anda benar
        version_label: "prod-${{ github.sha }}"
        deployment_package: deploy.zip
        use_existing_version_if_available: true
        