# .github/workflows/main.yml

name: Deploy to AWS Elastic Beanstalk

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Checkout kode dari repositori
    - name: Checkout source code
      uses: actions/checkout@v3

    # Langkah 2: Konfigurasi kredensial AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2 # GANTI dengan region AWS Anda (lihat di URL Elastic Beanstalk)

    # Langkah 3: Membuat file zip dari kode aplikasi
    - name: Zip our application code
      run: zip -r deploy.zip . -x ".git/*" ".github/*"

    # Langkah 4: Deploy ke Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: WebAppSaya             # GANTI dengan nama aplikasi EB Anda
        environment_name: WebAppSaya-env       # GANTI dengan nama environment EB Anda
        region: ap-southeast-2                   # GANTI dengan region AWS Anda
        version_label: ${{ github.sha }}         # Gunakan hash commit sebagai label versi
        deployment_package: deploy.zip           # File zip yang akan di-deploy